### ISSUE TITLE
Memberi warna/state yang berbeda saat menu terpilih

### ISSUE THREAD

**Issue by hilmanski** [hilmanski/koding#2]
Saat ini di sidebar ada daftar menu

![Screen Shot 2022-12-17 at 16 24 08](https://user-images.githubusercontent.com/4522467/208233007-a614591c-47a8-48f9-8f2d-d1744e60f931.png)

Akan lebih menarik jika membuat menu yang sedang terpilih, menjadi punya warna yang berbeda.

Warna yang bisa digunakan di tailwind: "text-sky-400"

Petunjuk:
Di hugo bisa mendeteksi .Permalink untuk link saat ini.
Lalu nanti perlu conditional if-else untuk menyelipkan jika Permalink sama dengan page yang saat ini sedang diloop, tambahkan kelas warna di atas

File yang perlu diubah:
/themes/twhugo/layouts/partials/chapterlist.md

**Comment by andrapratama** [comment]
file chapterlist yang mau diubah emang .md ya mas, bukan yg .html?

**Comment by hilmanski** [comment]
eh html betul! bukan md

**Comment by andrapratama** [comment]
siap mas

**Comment by hilmanski** [comment]
solved by @andrapratama 
thanks! 

Ref: https://github.com/hilmanski/koding/pull/3
