### ISSUE TITLE
Bug: referensi halaman tidak terlihat dengan lengkap

### ISSUE THREAD

**Issue by perdiDev** [hilmanski/koding#20]
![Capture](https://user-images.githubusercontent.com/108800230/215451294-3b8ab069-11c6-49bc-81ef-34ef1ab83759.PNG)

**Comment by perdiDev** [comment]
Bug juga terjadi pada halaman html

**Comment by halowahyudi** [comment]
bisa di scroll kak.

**Comment by perdiDev** [comment]
nggak bisa, kalau di device mu kelihatan semua?

**Comment by hilmanski** [comment]
Kalau devicenya pendek, mungkin memang akan terpotong.
Bisa diperbaiki dengan memberi jarak padding-bottom pada aside

**Comment by hilmanski** [comment]
solved in https://github.com/hilmanski/koding/commit/b8e68b973cac5034051fcab0c95583700d6bdb10
beritahu saya jika masih ada masalah ini
