### ISSUE TITLE
Iframe tailwindcss error

### ISSUE THREAD

**Issue by lakuapik** [hilmanski/koding#8]
<img width="821" alt="image" src="https://user-images.githubusercontent.com/20186786/208553325-eabbb032-1282-4cab-9919-73ce3b35e14d.png">

**Comment by hilmanski** [comment]
Apakah sampai sekarang saat kamu visit https://kodi.ng/html/format-text-html/
masih error? 

*Di browser saya tidak ada masalah

**Comment by lakuapik** [comment]
owalah, di chrome bisa sih mas:

<img width="873" alt="image" src="https://user-images.githubusercontent.com/20186786/208685223-5ca0b30c-53e1-47d0-bdd0-e2c31e70be65.png">

terakhir aku akses pake firefox masih error gitu. linknya yang ini https://kodi.ng/html/menggunakan-iframe-di-html.

**Comment by ajrulrn** [comment]
saya coba akses di firefox dan edge tidak ada masalah

![image](https://user-images.githubusercontent.com/50063588/213117382-b3ec5117-6b37-4e61-bd13-69d00a2ab6fe.png)

**Comment by lakuapik** [comment]
@ajrulrn mantap!

mungkin ini hanya terjadi di tempatku saja. aku akan close ini ya mas @hilmanski.
