### ISSUE TITLE
Menampilkan menu list di device kecil

### ISSUE THREAD

**Issue by hilmanski** [hilmanski/koding#9]
Saat ini menu list akan tersembunyi di device yang kecil.
https://github.com/hilmanski/koding/blob/main/themes/twhugo/layouts/partials/sidebar-chapters.html

**Task:**
Menampikan menu list dengan sifat bisa dibuka/tutup (toggle) saat di device berukuran kecil.

**Hint (Petunjuk):**
Bisa menggunakan trik collapsable sidebar ini: https://www.w3schools.com/howto/howto_js_collapse_sidebar.asp

**Lokasi file yang perlu diedit**
Halaman single layout
https://github.com/hilmanski/koding/blob/main/themes/twhugo/layouts/_default/single.html
Mainkan di bagian "sidebar-chapters"

**Comment by perdiDev** [comment]
Saya sudah berhasil menyelesaikan issue ini, tapi sedang menunggu review untuk PR sebelumnya kak @hilmanski

**Comment by perdiDev** [comment]
apakah saya bisa di assign untuk tugas ini kak @hilmanski?

**Comment by hilmanski** [comment]
sudah saya assign.
Terima kasih.

Silahkan didiskusikan dulu apa yang ingin dilakukan, jika sudah bisa disertakan gambar/video untuk bantu visual apa yang dilakukan

**Comment by perdiDev** [comment]
Saya menambahkahn button yang fixed di bagian bawah, tujuan agar lebih memudahkan pengguna untuk menavigasi.

![Button Expand](https://user-images.githubusercontent.com/108800230/216218864-80b92346-5378-4df0-9d4f-c629c374042f.PNG)


script javascript:

![Button Expand-code-script](https://user-images.githubusercontent.com/108800230/216218921-c4c3ca39-c7d8-4d56-9a78-1dd830104ee5.PNG)


Tampilan button fix dibagian bawah:

![Button Expand-interface-1](https://user-images.githubusercontent.com/108800230/216218965-d4a7f901-8a82-43a5-a388-5806e5706688.PNG)


Tampilan referensi halaman:

![Button Expand-interface-2](https://user-images.githubusercontent.com/108800230/216219064-6c8e0634-50bf-4b14-b453-6532185f1903.PNG)

**Comment by perdiDev** [comment]
Reviewnya kak @hilmanski

**Comment by hilmanski** [comment]
terima kasih @perdiDev sudah mengerjakan ini
saya ada beberapa saran revisi:

- posisi awal menu berada di atas. Kira2 sejajar dengan judul (tapi tetap fixed posisinya) , di sebelah kanan
- Untuk icon bisa gunakan https://tabler-icons.io/
bisa search "menu-2" dan ambil SVG nya

Thanks

**Comment by perdiDev** [comment]
apakah kalau disebelah kanan atas tidak mengganggu menu pencarian?

**Comment by hilmanski** [comment]
posisinya masih di bawah search. Sejajar dengan judul tapi di sebelah kanan (rata kanan) dengan akhir dari search

**Comment by perdiDev** [comment]
Posisi button:

![Button top right 1](https://user-images.githubusercontent.com/108800230/218601160-bd1c3230-f8f8-4274-936f-e60c97962b6a.PNG)

Tampilan setelah di expand:

![Button top right 2](https://user-images.githubusercontent.com/108800230/218601237-48d67631-61e7-4328-971e-d0133a11c17c.PNG)

#22 , kak @hilmanski bisa direview lagi

**Comment by hilmanski** [comment]
tolong diperhatikan lagi, masih ada issue CSS
cari di file CSS "<<<<<<< HEAD" yang ada bagian ini, ini issue yang perlu diresolve dulu sebelum commit

Cek pastikan di local semua sudah jalan sebelum push dan review
Thanks

**Comment by perdiDev** [comment]
Bisa direview ulang kak @hilmanski , sebelum di push sudah saya coba jalankan di lokal.

**Comment by hilmanski** [comment]
Terima kasih untuk kerja kerasnya @perdiDev 
sudah diaccpet ya PRnya
dengan sedikit improve di sini https://github.com/hilmanski/koding/pull/24
